### ISSUE TITLE
rosmetasys export -i crashes

### ISSUE THREAD

**Issue by jmachowinski** [vschroeter/rosmetasys-datasets#1]
~/ros2/ros2_ws/src$ rosmetasys export -i
Traceback (most recent call last):
  File "/home/jm/.local/bin/rosmetasys", line 5, in <module>
    from rosmetasys.cli import cli
  File "/home/jm/.local/lib/python3.10/site-packages/rosmetasys/cli.py", line 4, in <module>
    from click_aliases import ClickAliasedGroup
ModuleNotFoundError: No module named 'click_aliases'

Tried it with iron on ubuntu 22.04.

**Comment by vschroeter** [comment]
Added missing dependencies in new [Version 1.0.1](https://github.com/vschroeter/rosmetasys/releases/tag/1.0.1) ( https://github.com/vschroeter/rosmetasys/commit/6caaec649e942332d99301b735699d615aea9d48).

**Comment by jmachowinski** [comment]
that fixed the issue.
